bigassist-cms/bigassist_cms/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, include, url

from bigassist_cms.views import *

urlpatterns = patterns('',
	url(r'^photos/upload/$', 'bigassist_cms.views.upload_photos', name='cms_upload_photos'),
	url(r'^photos/recent/$', 'bigassist_cms.views.recent_photos', name='cms_recent_photos'),

    url(r'^page/(?P<section_slug>.*)/(?P<slug>.*)/', PageDetailView.as_view(), name='cms_page'),
    url(r'^section/(?P<section_slug>.*)/', PageListView.as_view(), name='cms_section'),

    url(r'^events/', EventListView.as_view(), name='cms_events'),
)

bigassist-cms/bigassist_cms/models.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.db import models

from django.utils.translation import gettext as _

from geoposition.fields import GeopositionField

from datetime import datetime
import os.path

class SectionManager(models.Manager):

    def available_in_nav(self):
        qs = self.filter(public=True)
        return qs


class Section(models.Model):
    title = models.CharField(max_length=250)
    slug = models.SlugField()
    created_on = models.DateTimeField(default=datetime.now, blank=True)
    modified_on = models.DateTimeField(auto_now=True, blank=True)
    public = models.BooleanField(default=True)
    in_navigation = models.BooleanField(default=True)
    order = models.PositiveIntegerField(default=0, blank=False, null=False)

    objects = SectionManager()

    class Meta:
        ordering = ('order',)
        verbose_name = _('Section')
        verbose_name_plural = _('Sections')

    def __unicode__(self):
        return self.title

    class Admin:
        pass


class PageManager(models.Manager):

    def public(self):
        qs = self.filter(
            public=True,
            parent__isnull=True,
            published_on__lt=datetime.now(),
            )
        return qs

    def news(self):
        qs = self.public().filter(section__slug='news').order_by('-published_on')
        return qs

    def guides(self):
        qs = self.public().filter(section__slug='guides')
        return qs


class Page(models.Model):
    title = models.CharField(max_length=250)
    slug = models.SlugField()
    introduction = models.TextField(blank=True)
    body = models.TextField(blank=True)
    created_on = models.DateTimeField(default=datetime.now, blank=True)
    published_on = models.DateTimeField(default=datetime.now, blank=True, help_text='Date to publish page')
    modified_on = models.DateTimeField(auto_now=True, blank=True)
    public = models.BooleanField(default=True)
    order = models.PositiveIntegerField(default=0, blank=False, null=False)

    section = models.ForeignKey('Section', blank=False)

    parent = models.ForeignKey('self', help_text='Choose the parent page', blank=True, null=True)

    objects = PageManager()

    class Meta:
        ordering = ('-order', '-published_on')
        # db_table = "bussinesses"

    def __unicode__(self):
        return self.title

    class Admin:
        pass


class File(models.Model):
    upload = models.FileField(upload_to="cms_uploads/%Y/%m/%d/")  # Appended to MEDIA_ROOT automatically
    created_on = models.DateTimeField(default=datetime.now)
    is_image = models.BooleanField(default=True)
    mime_type = models.CharField(max_length=255)


class AgendaItem(models.Model):
    order = models.IntegerField(default=0)
    time = models.TimeField(help_text='Add time in 24-hour format, like 10:45')
    text = models.TextField(blank=False)

    event = models.ForeignKey('Event')

    class Meta:
        verbose_name = "Agenda item"
        verbose_name_plural = "Agenda items"
        ordering = ('time', )

    def __unicode__(self):
        return u"{event} - {time}".format(event=self.event, time=self.time)


class Venue(models.Model):
    name = models.CharField(blank=False, max_length=255)
    slug = models.SlugField()

    address = models.TextField(blank=True, help_text="Full address, like: Society Building, 8 All Saints Road, London N1 9RL")
    city = models.CharField(blank=True, max_length=255)
    location = GeopositionField(blank=True)

    public = models.BooleanField(default=True)
    created_on = models.DateTimeField(default=datetime.now, blank=True)
    modified_on = models.DateTimeField(auto_now=True, blank=True)

    class Meta:
        verbose_name = "Venue"
        verbose_name_plural = "Venues"
        ordering = ('name', )

    def __unicode__(self):
        return u"{name} – {address}".format(name=self.name, address=self.address)


class Event(models.Model):
    title = models.CharField(blank=False, max_length=255)
    slug = models.SlugField()
    organiser = models.TextField(blank=True)
    date = models.DateField(blank=True, null=True)
    times = models.TextField(blank=True)
    audience = models.TextField(blank=True)

    text = models.TextField(blank=False)

    venue = models.ForeignKey(Venue, null=True, blank=True)

    eventbrite_link = models.URLField(blank=True)

    public = models.BooleanField(default=True)
    created_on = models.DateTimeField(default=datetime.now, blank=True)
    published_on = models.DateTimeField(default=datetime.now, blank=True, help_text='Date to publish event')
    modified_on = models.DateTimeField(auto_now=True, blank=True)

    class Meta:
        verbose_name = "Event"
        verbose_name_plural = "Events"
        ordering = ('date', )

    def __unicode__(self):
        return u"{date} – {title}".format(date=self.date, title=self.title)

bigassist-cms/bigassist_cms/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Create your views here.

import json

from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt  # cross-site request forgery
from django.views.decorators.http import require_POST

from django.views.generic import ListView, DetailView, TemplateView

from django.core.urlresolvers import reverse_lazy
from django.shortcuts import render, get_object_or_404

from django.contrib.auth.decorators import login_required

from models import File, Section, Page, Event


class PageDetailView(DetailView):
    model = Page
    template_name = 'page_detail.html'

    def get_context_data(self, **kwargs):
        context = super(PageDetailView, self).get_context_data(**kwargs)
        slug = self.kwargs.get('section_slug')
        context['section'] = get_object_or_404(Section, slug=slug)

        return context


class PageListView(ListView):
    model = Page
    template_name = 'page_list.html'
    paginate_by = 10
    section = None

    def get_queryset(self):
        self.section = get_object_or_404(Section, slug=self.slug)
        if self.slug == 'news':
            return Page.objects.news()
        elif self.slug == 'guides':
            return Page.objects.guides()
        else:
            return Page.objects.public().filter(section=self.section)

    def get(self, request, *args, **kwargs):
        self.slug = kwargs.get('section_slug')
        return super(PageListView, self).get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(PageListView, self).get_context_data(**kwargs)

        context['section'] = self.section

        return context


class EventListView(ListView):
    model = Event
    template_name = 'event_list.html'

    def get_context_data(self, **kwargs):
        context = super(EventListView, self).get_context_data(**kwargs)
        return context


# Views for image uploads

@csrf_exempt
@require_POST
@login_required
def upload_photos(request):
    images = []
    for f in request.FILES.getlist('file'):
        obj = File.objects.create(upload=f, is_image=True)
        images.append({'filelink': obj.upload.url})
    return HttpResponse(json.dumps(images), content_type='application/json')


@login_required
def recent_photos(request):
    images = [
        {'thumb': obj.upload.url, 'image': obj.upload.url}
        for obj in File.objects.filter(is_image=True).order_by('-created_on')[:20]
    ]
    return HttpResponse(json.dumps(images), content_type='application/json')

bigassist-cms/bigassist_cms/templates/event_list.html
{% extends 'base.html' %}
{% load url from future %}

{% block title %}BIG Assist programme of events 2015–16 - {{ block.super }}{% endblock %}

{% block content %}
<div class="width16">
	{# <div class="col col-twothirds"> #}
		<h1>BIG Assist programme of events 2015–16</h1>
		<div class="events">
		{% if event_list.count == 0 %}
			<p class="discreet">There are currently no events</p>
		{% endif %}
		{% for event in event_list %}
			<div class="event">
				<div class="event-meta width3 col">
					{% if event.date %}
						<h4 class="date">{{ event.date }}</h4>
					{% else %}
						<h4 class="date">Date TBC</h4>
					{% endif %}
					
					<p class="time">{{ event.times }}</p>
					{% if event.audience %}
						<h4>Audience</h4>
						<p class="audience">{{ event.audience }}</p>
					{% endif %}
					{% if event.eventbrite_link %}
						<p><a href="{{ event.eventbrite_link }}" class="link-button">Book on Eventbrite</a></p>
					{% endif %}
				</div>
				<div class="event-body width8 col" id="{{ event.slug }}">
					<h2>{{ event.title }}</h2>
					{% if event.organiser %}<p class="organiser discreet">{{ event.organiser }}</p>{% endif %}
					<div class="event-text">
						{% autoescape off %}
							{{ event.text }}
						{% endautoescape %}
					</div>
					{% if event.agendaitem_set.all %}
						<p><a href="#agenda" class="show-agenda" data-pid="{{ event.pk }}" data-text-swap="Hide agenda" data-text-original="Show agenda">Show agenda</a></p>
						<div class="agenda" id="event-agenda-{{ event.pk }}">
							<h3>Agenda</h3>
							<table>
							{% for item in event.agendaitem_set.all %}
								<tr>
									<td class="agenda-time">{{ item.time }}</td>
									<td class="agenda-text">{% autoescape off %}
										{{ item.text }}
									{% endautoescape %}</td>
								</tr>
							{% endfor %}
							</table>
						</div>
					{% endif %}
				</div>

				<div class="event-location width5 col last-col">
				{% if event.venue %}
					<h2>{% if event.venue.city %}
						{{ event.venue.city }}
					{% endif %}</h2>
					{% if event.venue %}
					<a href="http://maps.google.co.uk/maps?q={{ event.venue }}&amp;ll={{ event.venue.location|urlencode }}&amp;z=16">
						<img src="//maps.googleapis.com/maps/api/staticmap?center={{ event.venue_location }}&amp;zoom=14&amp;size=265x180&amp;maptype=roadmap&amp;markers=color:red%7Clabel:•%7C{{ event.venue.location }}&amp;key=AIzaSyAbAIZXiEqdQqA_XzdwsvVKJAxv44uRI8A" alt="Map of {{ event.venue }}" />
							<br />{{ event.venue|linebreaks }}
					</a>
					{% endif %}
				{% else %}
					<h2>Venue TBC</h2>
				{% endif %}
				</div>

			</div>
		{% endfor %}
		</div>
	{# </div> #}
</div>
{% endblock %}

{% block javascript_slot %}
<script>
  $(document).ready(function() {
    $('a.show-agenda').click(function(event) {
        event.preventDefault();
        $('div#event-agenda-' + $(this).data('pid')).slideToggle();

          var el = $(this);
          el.text() == el.data("text-swap") 
            ? el.text(el.data("text-original")) 
            : el.text(el.data("text-swap"));
    })


    $('.agenda').each(function(){
        $(this).hide();
    });


  });
</script>
{% endblock %}

bigassist-cms/bigassist_cms/templates/page_detail.html
{% extends 'base.html' %}
{% load url from future %}

{% block title %}{{ page.title }} – {{ page.section.title }} – {{ block.super }}{% endblock %}

{% block content %}

<div class="width16 cms-content">
	<div class="col col-twothirds">
		<h1>{{ page.title }}</h1>
		{% autoescape off %}
			<div class="introduction">
			{{ page.introduction }}
			</div>
			<div class="cms-body">
			{{ page.body }}
			</div>
			{% if page.section.slug == 'news' %}
				<p class="discreet published_on">Published on {{ page.published_on|date:"j F Y" }}</p>
			{% endif %}

		{% endautoescape %}
	</div>

	<div class="sections col col-third last-col">
		<h2><a href="{% url 'cms_section' page.section.slug %}">{{ page.section.title }}</a></h2>
		<ul>
		{% for p in section.page_set.all %}
			<li><a href="{% url 'cms_page' p.section.slug p.slug %}">{{ p.title }}</a></li>
		{% endfor %}
		</ul>
	</div>


</div>
{% endblock %}

bigassist-cms/bigassist_cms/templates/page_list.html
{% extends 'base.html' %}
{% load url from future %}

{% block title %}{{ section.title }} - {{ block.super }}{% endblock %}

{% block content %}
<div class="width16">
	<div class="col col-twothirds">
	<h1>{{ section }}</h1>
	{% for page in page_list %}
		<h2><a href="{% url 'cms_page' page.section.slug page.slug %}">{{ page.title }}</a></h2>

		{% autoescape off %}
			{{ page.introduction }}
		{% endautoescape %}

		{% if page.section.slug = 'news' %}
			<p class="discreet">Published on {{ page.published_on|date:"j F Y" }}</p>
		{% endif %}
		<p><a href="{% url 'cms_page' page.section.slug page.slug %}">Read more</a></p>
	{% endfor %}
	</div>
</div>
{% endblock %}